### ISSUE TITLE
Scott Git Reply May 31

### ISSUE THREAD

**Issue by Page007** [Page007/rutvikpage#10]
## Waterfall table: 

The successive filters applied to raw fee filing data: 
| Chars. of Raw Data. | Num. counties remaining (CC) | Num counties remaining (SC) | 
| -------------------  | ------------------- | -------------------  | 
| Raw Data   | 86 | 86 | 
| Drop counties with >1 CC Fees |  47 | 48 | 
| Drop counties facing treatment in 2017 | 46 | 47 |

## Treatment v/s control table: 

| Num Counties | CC | SC | 
| -------------------  | ------------------- | -------------------  | 
| Control | 8 | 35 | 
|Treatment | 38 | 12 | 
|Total | 46 | 47| 

- [x] Double checked if all counties are dropped! 

## Missing Values

The raw fee panel is unbalanced. If fees are missing for a year, the the value is left-imputed and if there is a spell of missing values, then it is dropped. 

## Treatment Timing

| Year | Num Treat. Counties (CC) | Num Treat counties (SC)| 
| -------------------  | ------------------- | -------------------  | 
| 2010 | 25 (mostly CA) | 1 | 
| 2011 |  2 | 3 |
| 2012 |  4 | 2 |
|2013|  0| 1 | 
|2014 | 2 | 0| 
|2015| 1 | 1 | 
|2016| 4 | 4| 
|Total | 38 | 12|   

### Asymmetric Binning

As you observe above, civil filing fee varies for 25 counties in 2010 of which we observe only 1 pre-period and all other pre-periods are binned together in it mechanically. On the other hand, only 5 counties are treated in 2015 and 2016 put together, of which we observe 6/7 pre-periods and all others (till -infty) are binned together in the last one (Boruskyak, Jaravel, Speiss). This causes over representation of later treated counties in 6th and 7th leads and gives noisy SE estimates. That is why the 6th and 7th leads are binned together.
I now realize that this is an enrichment issue and I should just have written it somewhere rather than implementing it. If you think this somehow induces noise in estimates, happy to remove it.

**Comment by rutvikpage** [comment]
## Specification Deliverables 

Because `amtPastDue` is highly skewed, OLS puts really heavy weights on thin tails. That is why I do not use it as a standalone outcome. The others are still kind of okay (at least the 75th percentiles are non zero) and so I do report level and logs regressions on those. 

If  $$y_{it} \in  (num30And60+ delinquencies, num90+ delinquencies)$$, then I run levels and logs specifications. The treatment cannot be logged, but the outcomes can be. The logs spec. will look like: 
$$\ln(y_{it}) = \alpha_{g(i)} + \alpha_t + \sum_{k = -6, k \neq -1}^{7} \beta_k \cdot 1 (t - E_i = k) + bin_{z(i), t} + \varepsilon_{it}$$
where $E_i$ is the time at which county $i$ experiences filing fee increase and $bin_{z(i), t}$ represents the number of people in different income bins at the zip level. The treatment can be civil/small claims fee increase. Therefore, in this series, we have 4 regressions. 

To use the variation in amtPastDue, I make another binary variable that turns on for an individual month if they have any amount past due and 1 30and 60+ delinquency rating and any 90+ delinquency rating. The logic for the threshold values here is the raw median value for these variables in the estimation sample. With this outcome, only a levels regression is possible. 

| Dependent Variable | Transformation | Treat: CC | Treat: SC | 
| ------------------- | ------------------- |------------------- | ------------------- |
| Num 30and 60 Ratings | Levels |  |  | 
| | Logs | link below| link below | 
|Num 90 + ratings | Levels | |  | 
| | Logs | |  | 
| Bin. outcome described above | levels | |  | 
| (`riskierThanMedian`) | | click [here](https://www.dropbox.com/scl/fo/yg7ymnhsrab2cjpwhrz3n/AKU7dtpCvEXEarPixd0gxx8?rlkey=nkh313v841xbyjvmiee86ptna&dl=0) | click [here](https://www.dropbox.com/scl/fo/p986lvfpdu6iug8o7qf31/APoKc51ZPcRVHhdmbTNxgbU?rlkey=k5qpdhjy7dqzoxbfg6ac7pmqd&dl=0)|

In all of the above regressions, I have controlled for zip level income.

## MVCs 

For missing values, the customs variables take negative values. I have dropped them because replacing them with zero would induce bias.
